name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Set up Pages
        uses: actions/configure-pages@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Create404
        run: cp ./scrpg-helper/dist/index.html ./scrpg-helper/dist/404.html
